name: 'AstroPanda.Data Publish'

trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: pipelines-template.yml

- task: DotNetCoreCLI@2
  displayName: 'publish package'
  inputs:
    command: publish
    projects: '**/*/AstroPanda.Data.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: 'AstroPanda'

