name: 'BasicRepos Publish'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: pipelines-template.yml

- task: DotNetCoreCLI@2
  displayName: 'create NuGet package'
  inputs:
    command: pack
    projects: '**/BasicRepos.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'    

