name: 'AstroPanda.Data Publish'

trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: pipelines-template.yml

- task: DotNetCoreCLI@2
  displayName: 'create NuGet package'
  inputs:
    command: pack
    projects: '**/AstroPanda.Data.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Push package to Astro Panda NuGet'
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: 'AstroPanda'

